### PR TITLE
remove H level from teaser title

### PR DESCRIPTION
**Pull request by lc512k**
This removes the H level from `n-teaser` title while preserving its style. 

Having `n-teaser` titles be `H`s is confusing for screen reader users, whose assistive tech strongly rely on HTML semantics. These H3/H2 elements end up being interpreted as subsection of whatever parent they're in, when they're really a standalone section.

cc @leggsimon @wheresrhys @keirog

### CODE REVIEW

**Comment by leggsimon** [comment]
Are they not a subsection of the parent they're in? I mean, each teaser in the top stories section is a subsection of the top stories no?

**Comment by lc512k** [comment]
@leggsimon, good question. Structurally, yes, it lives in that pace in the tree, but semantically? When a screen reader user pulls up a list of headers, often before they start interacting with the page, they expect to understand what the page is about from it, but for articles they get something like this:

H1 Donald Trump does outrageous thing
    H2 Related Article
        H3 More on this topic
    H2 Related Article

Which is not only useless to them, but misleading (I'm not sure we need much beyond H1 in article pages, tbh, but we're looking at that more closely soon)

Hs are useful for pages like the the front page, where they'd expect something like:

H1 Financial Times
    H2 UK News
    H2 Opinion
    H2 Video
    H2 Highlights

to get a sense of what is laid out in front of them (we don't do this exactly yet, we shove 100+ Hs into that list making it unnavigable to them, but we're working on that too)

**Comment by lc512k** [comment]
Found an article that does need H2s:

https://www.ft.com/content/378c2678-db9d-11e6-9d7c-be108f1c1dce

screen shot 2017-01-16 at 07 49 59

In this article, what should be an H2 is `The EU and the terms of Brexit`, etc, those are semantically a subsection of that article, something like

- H1 Trump’s UK trade pledge: hurdles to a quick deal
    - The EU and the terms of Brexit
    - Time
    - Duelling interests

But in this case, what they get is 

- H1 Trump’s UK trade pledge: hurdles to a quick deal
    - Related article
    - Related article

screen shot 2017-01-16 at 07 54 02

**Comment by lc512k** [comment]
Related to
Financial-Times/next-article#1767
Financial-Times/next-front-page#1436

**Comment by leggsimon** [comment]
Right ok. Thanks a lot for the write up! 👍

**Pull request merged**
